### ISSUE TITLE
AndroidRuntimeException: requestFeature() must be called before adding content

### ISSUE THREAD

**Issue by HanteIsHante** [HanteIsHante/file#11]
```
android.util.AndroidRuntimeException: requestFeature() must be called before adding content
                                                                                at com.android.internal.policy.PhoneWindow.requestFeature(PhoneWindow.java:317)
                                                                                at com.android.internal.app.AlertController.installContent(AlertController.java:231)
                                                                                at android.app.AlertDialog.onCreate(AlertDialog.java:423)
                                                                                at android.app.ProgressDialog.onCreate(ProgressDialog.java:198)
                                                                                at android.app.Dialog.dispatchOnCreate(Dialog.java:394)
                                                                                at android.app.Dialog.show(Dialog.java:295)

```

**Comment by HanteIsHante** [comment]
dialog.show()之前调用了dialog.setContentView()或者dialog.getwindow()等，正确的应该是dialog.show()之后调用dialog.setContentView()

**Comment by HanteIsHante** [comment]
```

public static ProgressDialog createProgressDialog(Context context) {
        ProgressDialog dialog = new ProgressDialog(context);
        try {
            dialog.show();
            dialog.setCancelable(false);
            if (dialog.getWindow() != null) {
                dialog.getWindow().setBackgroundDrawable(new ColorDrawable(android.graphics.Color.TRANSPARENT));
            }
            dialog.setContentView(R.layout.progres_dialog);
        } catch (Exception ignore) {
        }

        return dialog;
    }
```
