### ISSUE TITLE
Error: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.LinearLayout.setBackgroundColor(int)' on a null object reference

### ISSUE THREAD

**Issue by HanteIsHante** [HanteIsHante/file#12]
```
EventBus: Could not dispatch event: class net.netfits.android.netfits.base.domain.model.MessageEvent to subscribing class class net.netfits.android.netfits.base.SlideMenuFragment
                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.LinearLayout.setBackgroundColor(int)' on a null object reference
                                                                          at net.netfits.android.netfits.base.BaseFragment.onMessageEvent(BaseFragment.java:66)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
                                                                          at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:420)
                                                                          at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:397)
                                                                          at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:370)
                                                                          at org.greenrobot.eventbus.EventBus.post(EventBus.java:251)
                                                                          at net.netfits.android.netfits.service.VpnConnectionService$2$2.run(VpnConnectionService.java:93)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-01 11:56:12.174 779-887/? E/ConnectivityService: Unexpected mtu value: 0, tun0


```

**Comment by HanteIsHante** [comment]
mTopVpnState 报空指针

```
 @Subscribe(threadMode = ThreadMode.MAIN)
    public void onMessageEvent(MessageEvent msg) {
        if (msg.getShow().equals(Constant.CONN)) {
            show = true;
                  mTopVpnState.setBackgroundColor(getActivity().getResources().getColor(R.color.header_green_bar_color));
        } else if (msg.getShow().equals(Constant.DISCONN)) {
            show = false;
  mTopVpnState.setBackgroundColor(getActivity().getResources().getColor(R.color.header_light_red));
 
        }
    }


```
