### ISSUE TITLE
Package Manager Died

### ISSUE THREAD

**Issue by HanteIsHante** [HanteIsHante/file#17]
```
Process: cc.netpas.android_firewall, PID: 20258
java.lang.RuntimeException: Package manager has died
    at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:117)
    at net.netfits.android.netfits.paydialog.PayDetail.readDefaultStyle(PayDetail.java:263)
    at net.netfits.android.netfits.paydialog.PayDetail.setChannelList(PayDetail.java:974)
    at net.netfits.android.netfits.paydialog.PayPresenter$2.onSuccess(PayPresenter.java:80)
    at net.netfits.android.netfits.paydialog.PayPresenter$2.onSuccess(PayPresenter.java:77)
    at net.netfits.android.netfits.UseCaseThreadPoolScheduler$1.run(UseCaseThreadPoolScheduler.java:48)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5475)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:948)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:743)
 Caused by: android.os.TransactionTooLargeException
    at android.os.BinderProxy.transactNative(Native Method)
    at android.os.BinderProxy.transact(Binder.java:499)
    at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:1778)
    at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:112)
    at net.netfits.android.netfits.paydialog.PayDetail.readDefaultStyle(PayDetail.java:263) 
    at net.netfits.android.netfits.paydialog.PayDetail.setChannelList(PayDetail.java:974) 
    at net.netfits.android.netfits.paydialog.PayPresenter$2.onSuccess(PayPresenter.java:80) 
    at net.netfits.android.netfits.paydialog.PayPresenter$2.onSuccess(PayPresenter.java:77) 
    at net.netfits.android.netfits.UseCaseThreadPoolScheduler$1.run(UseCaseThreadPoolScheduler.java:48) 
    at android.os.Handler.handleCallback(Handler.java:739) 
    at android.os.Handler.dispatchMessage(Handler.java:95) 
    at android.os.Looper.loop(Looper.java:135) 
    at android.app.ActivityThread.main(ActivityThread.java:5475) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:372) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:948) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:743) 


```

**Comment by HanteIsHante** [comment]
尝试首先使用官方方式，然后如果失败，它会使用ADB命令获取包名，并逐个获取每个应用程序的信息
[参考链接](https://stackoverflow.com/questions/13235793/transactiontoolargeeception-when-trying-to-get-a-list-of-applications-installed/30062632#30062632)
```
 public static List<PackageInfo> getInstalledPackages(Context context,int flags)
    {
    final PackageManager pm=context.getPackageManager();
    try
      {
      return pm.getInstalledPackages(flags);
      }
    catch(Exception ignored)
      {
      //we don't care why it didn't succeed. We'll do it using an alternative way instead
      }
    // use fallback:
    Process process;
    List<PackageInfo> result=new ArrayList<>();
    BufferedReader bufferedReader=null;
    try
      {
      process=Runtime.getRuntime().exec("pm list packages");
      bufferedReader=new BufferedReader(new InputStreamReader(process.getInputStream()));
      String line;
      while((line=bufferedReader.readLine())!=null)
        {
        final String packageName=line.substring(line.indexOf(':')+1);
        final PackageInfo packageInfo=pm.getPackageInfo(packageName,flags);
        result.add(packageInfo);
        }
      process.waitFor();
      }
    catch(Exception e)
      {
      e.printStackTrace();
      }
    finally
      {
      if(bufferedReader!=null)
        try
          {
          bufferedReader.close();
          }
        catch(IOException e)
          {
          e.printStackTrace();
          }
      }
    return result;
    }


```

**Comment by HanteIsHante** [comment]
```
 PackageManager pM = mContext.getPackageManager();
        synchronized (PayStyleChooseAdapter.class) {
            try {
                pM.getPackageInfo("com.tencent.mm", PackageManager.GET_ACTIVITIES);
                return true;
            } catch (PackageManager.NameNotFoundException e) {
                return false;
            }
        }

```

 改为：

····
 pM.getApplicationInfo("com.tencent.mm", PackageManager.GET_META_DATA);
···
