### ISSUE TITLE
Notification ：java.lang.RuntimeException: bad array lengths

### ISSUE THREAD

**Issue by HanteIsHante** [HanteIsHante/file#20]
```
Fatal Exception: java.lang.RuntimeException: bad array lengths
       at android.os.Parcel.readIntArray(Parcel.java:905)
       at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:710)
       at android.app.NotificationManager.notify(NotificationManager.java:230)
       at android.app.NotificationManager.notify(NotificationManager.java:194)
       at net.netfits.android.netfits.service.ControllerService.showNotification(ControllerService.java:337)
       at net.netfits.android.netfits.service.ControllerService.access$200(ControllerService.java:38)
       at net.netfits.android.netfits.service.ControllerService$1.run(ControllerService.java:152)
       at android.os.Handler.handleCallback(Handler.java:743)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:150)
       at android.app.ActivityThread.main(ActivityThread.java:5546)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682)

```

     Notification notify = ShowNotify.showNotification(this, title, content);
     mNotificationManager.notify(VPN_STATE_NOTIFICATION_ID, notify);

**Comment by HanteIsHante** [comment]
[参考stackflow   Custom notification: java.lang.RuntimeException: bad array lengths](https://stackoverflow.com/questions/7988018/custom-notification-java-lang-runtimeexception-bad-array-lengths)

可能原因 重复使用同一个通知栏
