### ISSUE TITLE
Notification：Attempt to invoke interface method 'java.util.Iterator java.lang.Iterable.iterator()'

### ISSUE THREAD

**Issue by HanteIsHante** [HanteIsHante/file#21]
```

Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.lang.Iterable.iterator()' on a null object reference
       at android.app.ApplicationPackageManager.getUserIfProfile(ApplicationPackageManager.java:2256)
       at android.app.ApplicationPackageManager.getUserBadgeForDensity(ApplicationPackageManager.java:1044)
       at android.app.Notification$Builder.getProfileBadgeDrawable(Notification.java:3055)
       at android.app.Notification$Builder.hasThreeLines(Notification.java:3273)
       at android.app.Notification$Builder.build(Notification.java:3891)
       at android.support.v4.app.NotificationCompatApi21$Builder.build(NotificationCompatApi21.java:136)
       at android.support.v4.app.NotificationCompat$BuilderExtender.build(NotificationCompat.java:528)
       at android.support.v4.app.NotificationCompat$NotificationCompatImplApi21.build(NotificationCompat.java:835)
       at android.support.v4.app.NotificationCompat$Builder.build(NotificationCompat.java:1752)
       at net.netfits.android.netfits.util.ShowNotify.showNotification(ShowNotify.java:55)
       at net.netfits.android.netfits.service.ControllerService.showNotification(ControllerService.java:336)
       at net.netfits.android.netfits.service.ControllerService.access$200(ControllerService.java:38)
       at net.netfits.android.netfits.service.ControllerService$1.run(ControllerService.java:152)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5933)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:958)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:819)

```

**Comment by HanteIsHante** [comment]
notification = mNotificationBuilder.build();
        notification.flags = Notification.FLAG_ONGOING_EVENT;


 问题出现在：   _mNotificationBuilder.build();_
