### ISSUE TITLE
Error：Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by HanteIsHante** [HanteIsHante/file#22]
```
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1323)
       at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1341)
       at android.app.BackStackRecord.commitInternal(BackStackRecord.java:597)
       at android.app.BackStackRecord.commit(BackStackRecord.java:575)
       at android.app.DialogFragment.show(DialogFragment.java:230)
       at net.netfits.android.netfits.paydialog.PayDetail.onClick(PayDetail.java:300)
       at android.view.View.performClick(View.java:4630)
       at android.view.View$PerformClick.run(View.java:19339)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:157)
       at android.app.ActivityThread.main(ActivityThread.java:5335)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
       at dalvik.system.NativeStart.main(NativeStart.java)

```

在进行展示 DialogFragment  Show  时
```
PayStyleChoose payStyleChoose = new PayStyleChoose();
            if (netfitsServiceItem != null) {// 购买的item 条目详细信息
                Bundle bundle = new Bundle();
                bundle.putSerializable(BUYSERVICEITEM, netfitsServiceItem);
                payStyleChoose.setArguments(bundle);
            }
            payStyleChoose.setCancelable(false);
            payStyleChoose.show(getFragmentManager(), "pay_style");
```

show  源码中调用的是： commit()
```
public void show(FragmentManager manager, String tag) {
        mDismissed = false;
        mShownByMe = true;
        FragmentTransaction ft = manager.beginTransaction();
        ft.add(this, tag);
        ft.commit();
    }

```

错误解释：

commit方法是在Activity的onSaveInstanceState()之后调用的，这样会出错，因为onSaveInstanceState
方法是在该Activity即将被销毁前调用，来保存Activity数据的，如果在保存完状态后再给它添加Fragment就会出错。
如果展示fragment 时报此error:
解决办法就
是把commit（）方法替换成 commitAllowingStateLoss()就行了，其效果是一样的

**Comment by HanteIsHante** [comment]
##### 这是在 dialogFragment   show()  是发生

**Comment by HanteIsHante** [comment]
ok

**Comment by HanteIsHante** [comment]
[参考比较权威说明](http://www.androiddesignpatterns.com/2013/08/fragment-transaction-commit-state-loss.html)

**Comment by HanteIsHante** [comment]
[参考](https://stackoverflow.com/questions/14262312/java-lang-illegalstateexception-can-not-perform-this-action-after-onsaveinstanc)

我改变了下面的代码
`  
newFragment.show(transactionFragment, "dialog");
`
至：
`
transactionFragment.add(android.R.id.content, newFragment).addToBackStack(null).commitAllowingStateLoss();
`
