### ISSUE TITLE
IllegalArgumentException: Unknown URL content://downloads/my_downloads 系统下载管理器被禁用

### ISSUE THREAD

**Issue by HanteIsHante** [HanteIsHante/file#25]
```

Fatal Exception: java.lang.IllegalArgumentException: Unknown URL content://downloads/my_downloads
       at android.content.ContentResolver.insert(ContentResolver.java:1230)
       at android.app.DownloadManager.enqueue(DownloadManager.java:983)
       at net.netfits.android.netfits.util.FileDownLoadManager.startDownload(FileDownLoadManager.java:87)
       at net.netfits.android.netfits.base.BaseActivity.doDownLoadAPK(BaseActivity.java:396)
       at net.netfits.android.netfits.base.BaseActivity.askWritePermission(BaseActivity.java:387)
       at net.netfits.android.netfits.base.BaseActivity.access$100(BaseActivity.java:59)
       at net.netfits.android.netfits.base.BaseActivity$4.onClick(BaseActivity.java:353)


```

**Comment by HanteIsHante** [comment]
[参考 stackflow](https://stackoverflow.com/questions/21551538/how-to-enable-android-download-manager)

**Comment by HanteIsHante** [comment]
判定 系统下载管理器是否可用

```

static boolean downLoadMangerIsEnable(Context context) {
        int state = context.getApplicationContext().getPackageManager()
                .getApplicationEnabledSetting("com.android.providers.downloads");

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
            return !(state == PackageManager.COMPONENT_ENABLED_STATE_DISABLED ||
                    state == PackageManager.COMPONENT_ENABLED_STATE_DISABLED_USER
                    || state == PackageManager.COMPONENT_ENABLED_STATE_DISABLED_UNTIL_USED);
        } else {
            return !(state == PackageManager.COMPONENT_ENABLED_STATE_DISABLED ||
                    state == PackageManager.COMPONENT_ENABLED_STATE_DISABLED_USER);
        }
    }


```

**Comment by HanteIsHante** [comment]
打开 系统下载管理器 设置页面 或者 打开系统设置



```

try {
     //Open the specific App Info page:
     Intent intent = new Intent(android.provider.Settings.ACTION_APPLICATION_DETAILS_SETTINGS);
     intent.setData(Uri.parse("package:" + "com.android.providers.downloads"));
     startActivity(intent);

} catch ( ActivityNotFoundException e ) {
     e.printStackTrace();

     //Open the generic Apps page:
     Intent intent = new Intent(android.provider.Settings.ACTION_MANAGE_APPLICATIONS_SETTINGS);
     startActivity(intent);
}
```
