### ISSUE TITLE
oppo 8.1.0 :Fatal Exception: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1954)        at android.os.Handler.dispatchMessage(Handler.java:106)        at android.os.Looper.loop(Looper.java:197)        at android.app.ActivityThread.main(ActivityThread.java:6959)        at java.lang.reflect.Method.invoke(Method.java)        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514)        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)

### ISSUE THREAD

**Issue by HanteIsHante** [HanteIsHante/file#42]
`
Fatal Exception: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1954)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:197)
       at android.app.ActivityThread.main(ActivityThread.java:6959)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)

`

**Comment by HanteIsHante** [comment]
[参考解决方案](https://issuetracker.google.com/issues/76112072)


 在服务的onStartCommand（）中添加相同的逻辑。该应用程序有时会尝试启动已在运行的服务。它不会创建一个新的服务实例，它只是在已经通过onStartCommand（）运行的服务中调用它如果你在已经创建的服务上调用startForegroundService（）（即使它已经从onCreate（）调用startForeground（）一次]，你必须再次调用startForeground（）* *来自onStartCommand（）
