### ISSUE TITLE
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.android.gms.internal.firebase-perf.zzq.zzb(com.google.android.gms.internal.firebase-perf.zzah)' on a null object reference

### ISSUE THREAD

**Issue by HanteIsHante** [HanteIsHante/file#48]
```
08-03 12:03:38.211 20852-20969 E: Task exception on worker thread: java.lang.SecurityException: Failed to find provider com.google.android.gms.phenotype for user 0; expected to find a valid ContentProvider for this authority: com.google.android.gms.internal.measurement.zzwu.zza(Unknown Source:32)
08-03 12:03:38.212 20852-20969 E: Persisted config not initialized. Not logging error/warn
08-03 12:03:38.256 20852-20998 E: Google Play services missing or without correct permission.
08-03 12:03:38.551 20852-21038 E: failed to get ContentCatcherService.
08-03 12:03:38.551 20852-21038 E: failed to get ContentCatcherService.
08-03 12:03:38.648 20852-20969 E: Task exception on worker thread: java.lang.IllegalStateException: AppMeasurement is not initialized: com.google.android.gms.internal.measurement.zzgn.zzch(Unknown Source:8)
08-03 12:03:38.651 20852-20969 E: Task exception on worker thread: java.lang.IllegalStateException: Not initialized: com.google.android.gms.internal.measurement.zzhj.zzch(Unknown Source:10)
08-03 12:03:38.652 20852-20969 E: Persisted config not initialized. Not logging error/warn
    Persisted config not initialized. Not logging error/warn
08-03 12:03:38.680 20852-20994 E: FATAL EXCEPTION: pool-6-thread-1
    Process: world.letsgo.booster.android.pro, PID: 20852
    java.lang.SecurityException: Failed to find provider com.google.android.gsf.gservices for user 0; expected to find a valid ContentProvider for this authority
        at android.os.Parcel.readException(Parcel.java:2005)
        at android.os.Parcel.readException(Parcel.java:1951)
        at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:768)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1940)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1929)
        at com.google.android.gms.internal.firebase-perf.zza.zza(Unknown Source:38)
        at com.google.android.gms.internal.firebase-perf.zzq.<init>(Unknown Source:145)
        at com.google.android.gms.internal.firebase-perf.zzg.zzp(Unknown Source:127)
        at com.google.android.gms.internal.firebase-perf.zzg.zzb(Unknown Source:0)
        at com.google.android.gms.internal.firebase-perf.zzh.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
08-03 12:03:38.685 20852-21073 E: FATAL EXCEPTION: pool-6-thread-2
    Process: world.letsgo.booster.android.pro, PID: 20852
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.internal.firebase-perf.zzq.zzb(boolean)' on a null object reference
        at com.google.android.gms.internal.firebase-perf.zzg.zzc(Unknown Source:2)
        at com.google.android.gms.internal.firebase-perf.zzk.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
08-03 12:03:38.686 20852-21075 E: FATAL EXCEPTION: pool-6-thread-3
    Process: world.letsgo.booster.android.pro, PID: 20852
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.android.gms.internal.firebase-perf.zzq.zzb(com.google.android.gms.internal.firebase-perf.zzah)' on a null object reference
        at com.google.android.gms.internal.firebase-perf.zzg.zza(Unknown Source:169)
        at com.google.android.gms.internal.firebase-perf.zzg.zzb(Unknown Source:142)
        at com.google.android.gms.internal.firebase-perf.zzg.zza(Unknown Source:0)
        at com.google.android.gms.internal.firebase-perf.zzi.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
08-03 12:03:38.915 20852-21076 E: FATAL EXCEPTION: pool-6-thread-4
    Process: world.letsgo.booster.android.pro, PID: 20852
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.android.gms.internal.firebase-perf.zzq.zzb(com.google.android.gms.internal.firebase-perf.zzah)' on a null object reference
        at com.google.android.gms.internal.firebase-perf.zzg.zza(Unknown Source:169)
        at com.google.android.gms.internal.firebase-perf.zzg.zzb(Unknown Source:92)
        at com.google.android.gms.internal.firebase-perf.zzg.zza(Unknown Source:0)
        at com.google.android.gms.internal.firebase-perf.zzj.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
08-03 12:03:38.997 20852-21100 E: FATAL EXCEPTION: pool-6-thread-5
    Process: world.letsgo.booster.android.pro, PID: 20852
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.android.gms.internal.firebase-perf.zzq.zzb(com.google.android.gms.internal.firebase-perf.zzah)' on a null object reference
        at com.google.android.gms.internal.firebase-perf.zzg.zza(Unknown Source:169)
        at com.google.android.gms.internal.firebase-perf.zzg.zzb(Unknown Source:92)
        at com.google.android.gms.internal.firebase-perf.zzg.zza(Unknown Source:0)
        at com.google.android.gms.internal.firebase-perf.zzj.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
08-03 12:03:39.051 20852-21104 E: FATAL EXCEPTION: pool-6-thread-6
    Process: world.letsgo.booster.android.pro, PID: 20852
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.android.gms.internal.firebase-perf.zzq.zzb(com.google.android.gms.internal.firebase-perf.zzah)' on a null object reference
        at com.google.android.gms.internal.firebase-perf.zzg.zza(Unknown Source:169)
        at com.google.android.gms.internal.firebase-perf.zzg.zzb(Unknown Source:92)
        at com.google.android.gms.internal.firebase-perf.zzg.zza(Unknown Source:0)
        at com.google.android.gms.internal.firebase-perf.zzj.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
08-03 12:03:39.052 20852-20969 E: Task exception on worker thread: java.lang.IllegalStateException: AppMeasurement is not initialized: com.google.android.gms.internal.measurement.zzgn.zzch(Unknown Source:8)
    Persisted config not initialized. Not logging error/warn
08-03 12:03:39.073 20852-20969 E: Task exception on worker thread: java.lang.IllegalStateException: Not initialized: com.google.android.gms.internal.measurement.zzhj.zzch(Unknown Source:10)
08-03 12:03:39.073 20852-20969 E: Task exception on worker thread: java.lang.IllegalStateException: Not initialized: com.google.android.gms.internal.measurement.zzhj.zzch(Unknown Source:10)
08-03 12:03:39.074 20852-20969 E: Persisted config not initialized. Not logging error/warn
08-03 12:03:39.074 20852-20969 E: Persisted config not initialized. Not logging error/warn
08-03 12:03:39.088 20852-21038 E: failed to get ContentCatcherService.
08-03 12:03:39.089 20852-21038 E: failed to get ContentCatcherService.
08-03 12:03:39.305 20852-21105 E: FATAL EXCEPTION: pool-6-thread-7
    Process: world.letsgo.booster.android.pro, PID: 20852
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.android.gms.internal.firebase-perf.zzq.zzb(com.google.android.gms.internal.firebase-perf.zzah)' on a null object reference
        at com.google.android.gms.internal.firebase-perf.zzg.zza(Unknown Source:169)
        at com.google.android.gms.internal.firebase-perf.zzg.zzb(Unknown Source:92)
        at com.google.android.gms.internal.firebase-perf.zzg.zza(Unknown Source:0)
        at com.google.android.gms.internal.firebase-perf.zzj.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
08-03 12:03:39.306 20852-20969 E: Task exception on worker thread: java.lang.IllegalStateException: AppMeasurement is not initialized: com.google.android.gms.internal.measurement.zzgn.zzch(Unknown Source:8)
08-03 12:03:39.307 20852-20969 E: Task exception on worker thread: java.lang.IllegalStateException: Not initialized: com.google.android.gms.internal.measurement.zzhj.zzch(Unknown Source:10)
08-03 12:03:39.308 20852-20969 E: Persisted config not initialized. Not logging error/warn
08-03 12:03:39.313 20852-21148 E: FATAL EXCEPTION: pool-6-thread-8
    Process: world.letsgo.booster.android.pro, PID: 20852
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.android.gms.internal.firebase-perf.zzq.zzb(com.google.android.gms.internal.firebase-perf.zzah)' on a null object reference
        at com.google.android.gms.internal.firebase-perf.zzg.zza(Unknown Source:169)
        at com.google.android.gms.internal.firebase-perf.zzg.zzb(Unknown Source:92)
        at com.google.android.gms.internal.firebase-perf.zzg.zza(Unknown Source:0)
        at com.google.android.gms.internal.firebase-perf.zzj.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
08-03 12:03:39.308 20852-20969 E: Persisted config not initialized. Not logging error/warn
08-03 12:03:39.417 20852-21153 E: FATAL EXCEPTION: pool-6-thread-9
    Process: world.letsgo.booster.android.pro, PID: 20852
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.android.gms.internal.firebase-perf.zzq.zzb(com.google.android.gms.internal.firebase-perf.zzah)' on a null object reference
        at com.google.android.gms.internal.firebase-perf.zzg.zza(Unknown Source:169)
        at com.google.android.gms.internal.firebase-perf.zzg.zzb(Unknown Source:92)
        at com.google.android.gms.internal.firebase-perf.zzg.zza(Unknown Source:0)
        at com.google.android.gms.internal.firebase-perf.zzj.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
08-03 12:03:39.668 20852-21173 E: FATAL EXCEPTION: pool-6-thread-10
    Process: world.letsgo.booster.android.pro, PID: 20852
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.android.gms.internal.firebase-perf.zzq.zzb(com.google.android.gms.internal.firebase-perf.zzah)' on a null object reference
        at com.google.android.gms.internal.firebase-perf.zzg.zza(Unknown Source:169)
        at com.google.android.gms.internal.firebase-perf.zzg.zzb(Unknown Source:92)
        at com.google.android.gms.internal.firebase-perf.zzg.zza(Unknown Source:0)
        at com.google.android.gms.internal.firebase-perf.zzj.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
08-03 12:03:39.678 20852-21007 E: Can't find SessionUser data for session ID 5B63D41A011C-0001-5174-BD746870BCF9


```

**Comment by HanteIsHante** [comment]
[Firebase perfomance  stackoverflow 相似问题](https://stackoverflow.com/questions/50459628/com-google-android-gms-internal-firebase-perf-zzq-zzbboolean-on-a-null-object#)

**Comment by HanteIsHante** [comment]
android 8 以上设备，未安装google play 服务的均会出现此问题，安装google play 服务的设备不会出现此问题

**Comment by HanteIsHante** [comment]
暂时无解
