### ISSUE TITLE
Fatal Exception: java.lang.SecurityException Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) } without permission com.google.android.c2dm.permission.RECEIVE

### ISSUE THREAD

**Issue by HanteIsHante** [HanteIsHante/file#49]
集成 FireBase 后
```
Fatal Exception: java.lang.SecurityException
Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) } without permission com.google.android.c2dm.permission.RECEIVE
```
详细信息：
```
Fatal Exception: java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) } without permission com.google.android.c2dm.permission.RECEIVE
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1941)
       at android.app.ContextImpl.startService(ContextImpl.java:1918)
       at android.content.ContextWrapper.startService(ContextWrapper.java:527)
       at com.google.firebase.iid.zzan.zze(Unknown Source)
       at com.google.firebase.iid.zzan.zzd(Unknown Source)
       at com.google.firebase.iid.zzan.zzc(Unknown Source)
       at com.google.firebase.iid.zzo.zza(Unknown Source)
       at com.google.firebase.iid.zzp.run(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

```

**Comment by HanteIsHante** [comment]
[StackOverFlow 相似问题](https://stackoverflow.com/questions/25399845/securityexception-not-allowed-to-start-service-intent-act-com-google-android-c2)
