### ISSUE TITLE
Fatal Exception: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)

### ISSUE THREAD

**Issue by HanteIsHante** [HanteIsHante/file#52]
```
Fatal Exception: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
       at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)
       at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
       at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
       at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1579)
       at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1525)
   )
db.update()
```

**Comment by HanteIsHante** [comment]
同 #54
