### ISSUE TITLE
问题：FATAL EXCEPTION: main Process: com.android.vending, PID: 11320 java.lang.OutOfMemoryError: Failed to allocate a 524300 byte allocation with 485596 free bytes and 474KB until OOM

### ISSUE THREAD

**Issue by HanteIsHante** [HanteIsHante/file#59]
Galaxy J1 Ace

制造商
Samsung
OpenGL ES 版本
2.0
Android 版本
Android 5.1
原生平台
armeabi-v7a
语言区域
zh
CPU 品牌
Spreadtrum
CPU 型号
SC9830I

屏幕尺寸

480 × 800
测试持续时间

300 秒
屏幕密度 (dpi)
240
型号名称
Galaxy J1 Ace
RAM
1024 MB

**Comment by HanteIsHante** [comment]
```
 FATAL EXCEPTION: main
Process: com.android.vending, PID: 11320
java.lang.OutOfMemoryError: Failed to allocate a 524300 byte allocation with 485596 free bytes and 474KB until OOM
	at java.util.HashMap.makeTable(HashMap.java:550)
	at java.util.HashMap.<init>(HashMap.java:158)
	at java.util.HashMap.<init>(HashMap.java:195)
	at android.app.SharedPreferencesImpl$EditorImpl.commitToMemory(SharedPreferencesImpl.java:399)
	at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:359)
	at com.google.android.finsky.ah.q.a(q.java:10)
	at com.google.android.finsky.hygiene.impl.e.i(e.java:124)
	at com.google.android.finsky.hygiene.impl.e.c(e.java:45)
	at com.google.android.finsky.accounts.impl.AccountsChangedReceiver.a(AccountsChangedReceiver.java:50)
	at com.google.android.finsky.ab.a.onReceive(a.java:5)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3518)
	at android.app.ActivityThread.access$1900(ActivityThread.java:218)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1811)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6934)
	at java.lang.reflect.Method.invoke(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```
