### ISSUE TITLE
Service AIDL 发生DeadObjectException

### ISSUE THREAD

**Issue by HanteIsHante** [HanteIsHante/file#61]
```
Caused by android.os.DeadObjectException
       at android.os.BinderProxy.transactNative(Binder.java)
       at android.os.BinderProxy.transact(Binder.java:748)
       at packageName$Stub$Proxy.getState(IProxyService.java:138)
       at packageName.BaseActivity.onServiceConnected(BaseActivity.kt:75)
```

**Comment by HanteIsHante** [comment]
[参考](https://blog.csdn.net/qq_26643587/article/details/80237582)

**Comment by HanteIsHante** [comment]
可能还会产生这个问题，可以添加上 try...catch..
