### ISSUE TITLE
Caused by android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed

### ISSUE THREAD

**Issue by HanteIsHante** [HanteIsHante/file#64]
```
Caused by android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
       at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:270)
       at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:330)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
       at android.webkit.WebView.getFactory(WebView.java:2325)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2320)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2379)
       at android.view.View.(View.java:4027)
       at android.view.View.(View.java:4150)
       at android.view.ViewGroup.(ViewGroup.java:582)
       at android.widget.AbsoluteLayout.(AbsoluteLayout.java:55)
       at android.webkit.WebView.(WebView.java:627)
       at android.webkit.WebView.(WebView.java:572)
       at android.webkit.WebView.(WebView.java:555)
       at android.webkit.WebView.(WebView.java:542)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
       at android.view.LayoutInflater.createView(LayoutInflater.java:645)
       at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
       at world.letsgo.booster.android.base.BaseFragment.onCreateView(BaseFragment.kt:16)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
       at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
       at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1341)
       at android.app.Activity.performStart(Activity.java:6765)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2947)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
       at android.app.ActivityThread.-wrap13(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1660)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:171)
       at android.app.ActivityThread.main(ActivityThread.java:6668)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:797)

```

原因是设备系统中未存在 webview

**Comment by HanteIsHante** [comment]
[部分机型没有WebView，应用直接崩溃](https://iluhcm.com/2017/12/10/design-an-elegant-and-powerful-android-webview-part-one/)
